---

- name: Añadir repo elasticsearch en Rhel
  when: ansible_os_family == "RedHat"
  block:
  - name: Añadir repo elasticsearch
    ansible.builtin.yum_repository:
      name: elasticsearch
      description: elasticsearch repo
      baseurl: "https://artifacts.elastic.co/packages/{{ version }}/yum"
      gpgcheck: false


- name: Instalar logstash
  ansible.builtin.package:
    name: logstash
    state: present
    update_cache: true


- name: Crear ficheros configuracion
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: '0644'
  with_items:
     - 02-input-beat.conf    
     - 30-elasticsearch-output.conf
     - 10-syslog-filter.conf
    # - logstash.conf


- name: Habilitar servicio
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: true


- name: Permitir trafico por puerto de elasticsearch
  ansible.posix.firewalld:
    port: 5044/tcp
    state: enabled
    permanent: true
    immediate: true
  when: ansible_os_family == "RedHat" 

...