---

- name: Instalar logstash
  ansible.builtin.package:
    name: logstash
    state: present
    update_cache: true


- name: Crear fichero configuracion
  ansible.builtin.copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: '0644'


- name: Habilitar servicio
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: true


- name: Lanzar configuracion logstash para activar servidor
  ansible.builtin.shell:
    cmd: /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf > logstash.log 2>&1 &
  changed_when: false


- name: Esperar a puerto 5044
  ansible.builtin.wait_for:
    port: 5044
    delay: 10


- name: Permitir trafico por puerto de logstash
  ansible.posix.firewalld:
    port: 5044/tcp
    state: enabled
    permanent: true
    immediate: true
  when: ansible_os_family == "RedHat" 

...