---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    - servicio: filebeat
  tasks:
    - name: Iniciar servicio {{ servicio }}
      ansible.builtin.service:
        name: "{{ servicio }}"
        state: started
      register: status
  

    - name: Comprobar servicio
      ansible.builtin.assert:
        that: not status.changed
        success_msg: "{{ servicio }} corriendo"
        fail_msg: "{{ servicio }} no esta corriendo"

...