---

- name: Instalar Kibana
  ansible.builtin.package:
    name: kibana
    state: present
    update_cache: true


- name: Configuracion kibana
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { path: /etc/kibana/kibana.yml,
        regexp: "^#server.port",
        line: "server.port: 5601"
      }
    - { path: /etc/kibana/kibana.yml,
        regexp: "^#server.host",
        line: 'server.host: "0.0.0.0"'
      }    
    - { path: /etc/kibana/kibana.yml,
        regexp: "^#elasticsearch.hosts",
        line: 'elasticsearch.hosts: ["http://localhost:9200"]'
      }  


- name: Habilitar servicio kibana
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: true


- name: Habilitar puerto kibana
  ansible.posix.firewalld:
    port: 5601/tcp
    state: enabled
    permanent: true
    immediate: true    

...